# GENERATED by scripts/build-schema.mjs from schema/editor/model.json — DO NOT EDIT.
# Run `npm run build:schema` after editing the model.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

Role = Literal["figure", "panel", "axis", "series", "legend", "title", "annotation", "colorbar"]
EditState = Literal["editable", "readonly", "unsupported"]
TraversalStatus = Literal["represented", "consumed", "internal", "unsupported"]
EngineId = Literal["matplotlib", "vega"]
ApplyErrorCode = Literal["stale_revision", "unknown_node", "unknown_component", "unknown_property", "not_editable", "invalid_value", "apply_failed", "not_implemented"]
CommandType = Literal["set"]
ViewKind = Literal["svg"]

ROLES: tuple[Role, ...] = ("figure", "panel", "axis", "series", "legend", "title", "annotation", "colorbar",)
EDIT_STATES: tuple[EditState, ...] = ("editable", "readonly", "unsupported",)
TRAVERSAL_STATUSES: tuple[TraversalStatus, ...] = ("represented", "consumed", "internal", "unsupported",)
ENGINE_IDS: tuple[EngineId, ...] = ("matplotlib", "vega",)
APPLY_ERROR_CODES: tuple[ApplyErrorCode, ...] = ("stale_revision", "unknown_node", "unknown_component", "unknown_property", "not_editable", "invalid_value", "apply_failed", "not_implemented",)
COMPONENT_NAMES: tuple[str, ...] = ("transform", "geometry", "appearance", "stroke", "fill", "text", "typography", "marker", "layout", "axis", "binding", "source",)


@dataclass
class BBox:
    x: float
    y: float
    w: float
    h: float


@dataclass
class Transform:
    pass

@dataclass
class Geometry:
    bbox: BBox | None = None

@dataclass
class Appearance:
    visible: bool | None = None
    opacity: float | None = None
    zIndex: float | None = None

@dataclass
class Stroke:
    color: str | None = None
    width: float | None = None
    opacity: float | None = None
    dash: list[float] | None = None

@dataclass
class Fill:
    color: str | None = None
    opacity: float | None = None

@dataclass
class Text:
    content: str | None = None

@dataclass
class Typography:
    family: str | None = None
    size: float | None = None
    weight: str | None = None
    style: str | None = None
    color: str | None = None

@dataclass
class Marker:
    shape: str | None = None
    size: float | None = None
    color: str | None = None

@dataclass
class Layout:
    width: float | None = None
    height: float | None = None
    xMin: float | None = None
    xMax: float | None = None
    yMin: float | None = None
    yMax: float | None = None

@dataclass
class Axis:
    min: float | None = None
    max: float | None = None
    ticks: list[float] | None = None
    tickLabels: list[str] | None = None
    format: str | None = None
    scale: str | None = None

@dataclass
class Binding:
    pass

@dataclass
class Source:
    pass


@dataclass
class Components:
    transform: Transform | None = None
    geometry: Geometry | None = None
    appearance: Appearance | None = None
    stroke: Stroke | None = None
    fill: Fill | None = None
    text: Text | None = None
    typography: Typography | None = None
    marker: Marker | None = None
    layout: Layout | None = None
    axis: Axis | None = None
    binding: Binding | None = None
    source: Source | None = None


Editability = dict[str, dict[str, EditState]]


@dataclass
class Node:
    id: str
    role: Role
    children: list[Node] = field(default_factory=list)
    components: Components = field(default_factory=Components)
    editability: Editability = field(default_factory=dict)
    label: str | None = None


@dataclass
class Scene:
    engine_id: EngineId
    root: Node


@dataclass
class View:
    kind: ViewKind
    svg: str


@dataclass
class TraversalEntry:
    ref: str
    status: TraversalStatus
    node_id: str | None = None
    detail: str | None = None


@dataclass
class Diagnostics:
    traversal: list[TraversalEntry] = field(default_factory=list)


@dataclass
class RenderResult:
    request_id: str
    revision: int
    scene: Scene
    view: View
    diagnostics: Diagnostics


@dataclass
class SetCommand:
    node_id: str
    component: str
    property: str
    value: Any
    base_revision: int
    type: CommandType = "set"


Command = SetCommand


@dataclass
class ApplyError:
    code: ApplyErrorCode
    message: str


@dataclass
class ApplyResult:
    request_id: str
    ok: bool
    error: ApplyError | None = None
    result: RenderResult | None = None
