// GENERATED by scripts/build-schema.mjs from schema/editor/model.json — DO NOT EDIT.
// Run `npm run build:schema` after editing the model.

export type Role = "figure" | "panel" | "axis" | "series" | "legend" | "title" | "annotation" | "colorbar";
export type EditState = "editable" | "readonly" | "unsupported";
export type TraversalStatus = "represented" | "consumed" | "internal" | "unsupported";
export type EngineId = "matplotlib" | "vega";
export type ApplyErrorCode = "stale_revision" | "unknown_node" | "unknown_component" | "unknown_property" | "not_editable" | "invalid_value" | "apply_failed" | "not_implemented";
export type CommandType = "set";
export type ViewKind = "svg";

export const ROLES = ["figure","panel","axis","series","legend","title","annotation","colorbar"] as const;
export const EDIT_STATES = ["editable","readonly","unsupported"] as const;
export const TRAVERSAL_STATUSES = ["represented","consumed","internal","unsupported"] as const;
export const ENGINE_IDS = ["matplotlib","vega"] as const;
export const APPLY_ERROR_CODES = ["stale_revision","unknown_node","unknown_component","unknown_property","not_editable","invalid_value","apply_failed","not_implemented"] as const;
export const COMPONENT_NAMES = ["transform","geometry","appearance","stroke","fill","text","typography","marker","layout","axis","binding","source"] as const;

export interface BBox {
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export interface Transform {

}

export interface Geometry {
  readonly bbox?: BBox;
}

export interface Appearance {
  readonly visible?: boolean;
  readonly opacity?: number;
  readonly zIndex?: number;
}

export interface Stroke {
  readonly color?: string;
  readonly width?: number;
  readonly opacity?: number;
  readonly dash?: readonly number[];
}

export interface Fill {
  readonly color?: string;
  readonly opacity?: number;
}

export interface Text {
  readonly content?: string;
}

export interface Typography {
  readonly family?: string;
  readonly size?: number;
  readonly weight?: string;
  readonly style?: string;
  readonly color?: string;
}

export interface Marker {
  readonly shape?: string;
  readonly size?: number;
  readonly color?: string;
}

export interface Layout {
  readonly width?: number;
  readonly height?: number;
  readonly xMin?: number;
  readonly xMax?: number;
  readonly yMin?: number;
  readonly yMax?: number;
}

export interface Axis {
  readonly min?: number;
  readonly max?: number;
  readonly ticks?: readonly number[];
  readonly tickLabels?: readonly string[];
  readonly format?: string;
  readonly scale?: string;
}

export interface Binding {

}

export interface Source {

}

export interface Components {
  readonly transform?: Transform;
  readonly geometry?: Geometry;
  readonly appearance?: Appearance;
  readonly stroke?: Stroke;
  readonly fill?: Fill;
  readonly text?: Text;
  readonly typography?: Typography;
  readonly marker?: Marker;
  readonly layout?: Layout;
  readonly axis?: Axis;
  readonly binding?: Binding;
  readonly source?: Source;
}

export type ComponentName = "transform" | "geometry" | "appearance" | "stroke" | "fill" | "text" | "typography" | "marker" | "layout" | "axis" | "binding" | "source";

export type Editability = {
  readonly [K in ComponentName]?: { readonly [property: string]: EditState };
};

export interface Node {
  readonly id: string;
  readonly role: Role;
  readonly label?: string;
  readonly children: readonly Node[];
  readonly components: Components;
  readonly editability: Editability;
}

export interface Scene {
  readonly engineId: EngineId;
  readonly root: Node;
}

export interface View {
  readonly kind: ViewKind;
  readonly svg: string;
}

export interface TraversalEntry {
  readonly ref: string;
  readonly status: TraversalStatus;
  readonly nodeId?: string;
  readonly detail?: string;
}

export interface Diagnostics {
  readonly traversal: readonly TraversalEntry[];
}

export interface RenderResult {
  readonly requestId: string;
  readonly revision: number;
  readonly scene: Scene;
  readonly view: View;
  readonly diagnostics: Diagnostics;
}

export interface SetCommand {
  readonly type: "set";
  readonly nodeId: string;
  readonly component: ComponentName;
  readonly property: string;
  readonly value: unknown;
  readonly baseRevision: number;
}

export type Command = SetCommand;

export interface ApplyError {
  readonly code: ApplyErrorCode;
  readonly message: string;
}

export interface ApplyResult {
  readonly requestId: string;
  readonly ok: boolean;
  readonly error?: ApplyError;
  readonly result?: RenderResult;
}
