#!/usr/bin/env node
/**
 * build-schema — compiler for the MolPlot editor contract.
 *
 * Reads `schema/editor/model.json` (the only hand-edited copy) and emits:
 *
 *   core/src/semantic/generated.ts
 *   python/src/molplot/semantic/_generated.py
 *
 * Output is deterministic so CI can run `--check`. Never hand-edit the
 * generated files.
 *
 * Usage:  node scripts/build-schema.mjs [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MODEL = join(ROOT, "schema", "editor", "model.json");
const TS_OUT = join(ROOT, "core", "src", "semantic", "generated.ts");
const PY_OUT = join(
  ROOT,
  "python",
  "src",
  "molplot",
  "semantic",
  "_generated.py",
);
const check = process.argv.includes("--check");

const model = JSON.parse(readFileSync(MODEL, "utf8"));

const union = (values) => values.map((v) => `"${v}"`).join(" | ");
const pyLiteral = (name, values) =>
  `${name} = Literal[${values.map((v) => `"${v}"`).join(", ")}]`;

function tsField(name, typ) {
  if (typ === "BBox") return `readonly ${name}?: BBox;`;
  if (typ === "boolean") return `readonly ${name}?: boolean;`;
  if (typ === "number") return `readonly ${name}?: number;`;
  if (typ === "string") return `readonly ${name}?: string;`;
  if (typ === "number[]") return `readonly ${name}?: readonly number[];`;
  if (typ === "string[]") return `readonly ${name}?: readonly string[];`;
  throw new Error(`unknown field type ${typ} for ${name}`);
}

function pyField(name, typ) {
  if (typ === "BBox") return `    ${name}: BBox | None = None`;
  if (typ === "boolean") return `    ${name}: bool | None = None`;
  if (typ === "number") return `    ${name}: float | None = None`;
  if (typ === "string") return `    ${name}: str | None = None`;
  if (typ === "number[]") return `    ${name}: list[float] | None = None`;
  if (typ === "string[]") return `    ${name}: list[str] | None = None`;
  throw new Error(`unknown field type ${typ} for ${name}`);
}

function pascal(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function renderTs() {
  const comps = model.components;
  const compIfaces = Object.entries(comps)
    .map(([name, fields]) => {
      const body = Object.entries(fields)
        .map(([k, t]) => `  ${tsField(k, t)}`)
        .join("\n");
      return `export interface ${pascal(name)} {\n${body}\n}`;
    })
    .join("\n\n");

  const compKeys = Object.keys(comps)
    .map((n) => `  readonly ${n}?: ${pascal(n)};`)
    .join("\n");

  const names = Object.keys(comps)
    .map((n) => `"${n}"`)
    .join(" | ");

  return `// GENERATED by scripts/build-schema.mjs from schema/editor/model.json — DO NOT EDIT.
// Run \`npm run build:schema\` after editing the model.

export type Role = ${union(model.role)};
export type EditState = ${union(model.editState)};
export type TraversalStatus = ${union(model.traversalStatus)};
export type EngineId = ${union(model.engineId)};
export type ApplyErrorCode = ${union(model.applyErrorCode)};
export type CommandType = ${union(model.commandType)};
export type ViewKind = ${union(model.viewKind)};

export const ROLES = ${JSON.stringify(model.role)} as const;
export const EDIT_STATES = ${JSON.stringify(model.editState)} as const;
export const TRAVERSAL_STATUSES = ${JSON.stringify(model.traversalStatus)} as const;
export const ENGINE_IDS = ${JSON.stringify(model.engineId)} as const;
export const APPLY_ERROR_CODES = ${JSON.stringify(model.applyErrorCode)} as const;
export const COMPONENT_NAMES = ${JSON.stringify(Object.keys(comps))} as const;

export interface BBox {
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

${compIfaces}

export interface Components {
${compKeys}
}

export type ComponentName = ${names};

export type Editability = {
  readonly [K in ComponentName]?: { readonly [property: string]: EditState };
};

export interface Node {
  readonly id: string;
  readonly role: Role;
  readonly label?: string;
  readonly children: readonly Node[];
  readonly components: Components;
  readonly editability: Editability;
}

export interface Scene {
  readonly engineId: EngineId;
  readonly root: Node;
}

export interface View {
  readonly kind: ViewKind;
  readonly svg: string;
}

export interface TraversalEntry {
  readonly ref: string;
  readonly status: TraversalStatus;
  readonly nodeId?: string;
  readonly detail?: string;
}

export interface Diagnostics {
  readonly traversal: readonly TraversalEntry[];
}

export interface RenderResult {
  readonly requestId: string;
  readonly revision: number;
  readonly scene: Scene;
  readonly view: View;
  readonly diagnostics: Diagnostics;
}

export interface SetCommand {
  readonly type: "set";
  readonly nodeId: string;
  readonly component: ComponentName;
  readonly property: string;
  readonly value: unknown;
  readonly baseRevision: number;
}

export type Command = SetCommand;

export interface ApplyError {
  readonly code: ApplyErrorCode;
  readonly message: string;
}

export interface ApplyResult {
  readonly requestId: string;
  readonly ok: boolean;
  readonly error?: ApplyError;
  readonly result?: RenderResult;
}
`;
}

function renderPy() {
  const comps = model.components;
  const classes = Object.entries(comps)
    .map(([name, fields]) => {
      const entries = Object.entries(fields);
      const body =
        entries.length === 0
          ? "    pass"
          : entries.map(([k, t]) => pyField(k, t)).join("\n");
      return `@dataclass
class ${pascal(name)}:
${body}`;
    })
    .join("\n\n");

  const compFields = Object.keys(comps)
    .map((n) => `    ${n}: ${pascal(n)} | None = None`)
    .join("\n");

  const names = Object.keys(comps)
    .map((n) => `"${n}"`)
    .join(", ");

  return `# GENERATED by scripts/build-schema.mjs from schema/editor/model.json — DO NOT EDIT.
# Run \`npm run build:schema\` after editing the model.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

${pyLiteral("Role", model.role)}
${pyLiteral("EditState", model.editState)}
${pyLiteral("TraversalStatus", model.traversalStatus)}
${pyLiteral("EngineId", model.engineId)}
${pyLiteral("ApplyErrorCode", model.applyErrorCode)}
${pyLiteral("CommandType", model.commandType)}
${pyLiteral("ViewKind", model.viewKind)}

ROLES: tuple[Role, ...] = (${model.role.map((v) => `"${v}"`).join(", ")},)
EDIT_STATES: tuple[EditState, ...] = (${model.editState.map((v) => `"${v}"`).join(", ")},)
TRAVERSAL_STATUSES: tuple[TraversalStatus, ...] = (${model.traversalStatus.map((v) => `"${v}"`).join(", ")},)
ENGINE_IDS: tuple[EngineId, ...] = (${model.engineId.map((v) => `"${v}"`).join(", ")},)
APPLY_ERROR_CODES: tuple[ApplyErrorCode, ...] = (${model.applyErrorCode.map((v) => `"${v}"`).join(", ")},)
COMPONENT_NAMES: tuple[str, ...] = (${names},)


@dataclass
class BBox:
    x: float
    y: float
    w: float
    h: float


${classes}


@dataclass
class Components:
${compFields}


Editability = dict[str, dict[str, EditState]]


@dataclass
class Node:
    id: str
    role: Role
    children: list[Node] = field(default_factory=list)
    components: Components = field(default_factory=Components)
    editability: Editability = field(default_factory=dict)
    label: str | None = None


@dataclass
class Scene:
    engine_id: EngineId
    root: Node


@dataclass
class View:
    kind: ViewKind
    svg: str


@dataclass
class TraversalEntry:
    ref: str
    status: TraversalStatus
    node_id: str | None = None
    detail: str | None = None


@dataclass
class Diagnostics:
    traversal: list[TraversalEntry] = field(default_factory=list)


@dataclass
class RenderResult:
    request_id: str
    revision: int
    scene: Scene
    view: View
    diagnostics: Diagnostics


@dataclass
class SetCommand:
    node_id: str
    component: str
    property: str
    value: Any
    base_revision: int
    type: CommandType = "set"


Command = SetCommand


@dataclass
class ApplyError:
    code: ApplyErrorCode
    message: str


@dataclass
class ApplyResult:
    request_id: str
    ok: bool
    error: ApplyError | None = None
    result: RenderResult | None = None
`;
}

function writeOut(path, content) {
  const body = content.endsWith("\n") ? content : `${content}\n`;
  if (check) {
    const onDisk = readFileSync(path, "utf8");
    if (onDisk !== body) {
      console.error(`schema drift: ${path} is stale. Run npm run build:schema`);
      process.exit(1);
    }
    return;
  }
  writeFileSync(path, body);
}

writeOut(TS_OUT, renderTs());
writeOut(PY_OUT, renderPy());
if (!check) {
  console.log("wrote", TS_OUT);
  console.log("wrote", PY_OUT);
} else {
  console.log("schema generated files in sync");
}
